FROM puppet/pdk:latest

# [Optional] Uncomment this section to install additional packages.
# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#     && apt-get -y install --no-install-recommends <your-package-list-here>

Sggest Docker-Container
'rest.office365.com'
* cdn.offic.net
*fluidprism.offic.net

- parse stylesheet index, script-src 'nonce-kr3Mg+MZ/rFL+ GRVN0CdQ=='
