FROM puppet/pdk:latest

# [Optional] Uncomment this section to install additional packages.
# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#     && apt-get -y install --no-install-recommends <your-package-list-here>

Sggest Docker-Container
'rest.office365.com'
* cdn.offic.net
*fluidprism.offic.net

- parse stylesheet index, script-src 'nonce-kr3Mg+MZ/rFL+ GRVN0CdQ=='

X-MS-Exchange-CrossTenant-id: 84df9e7f-e9f6-40af-b435-aaaaaaaaaaaa
X-MS-Exchange-CrossTenant-AuthSource: CWLP265MB4626.GBRP265.PROD.OUTLOOK.COM

x-ms-exchange-antispam-messagedata-0: =?iso-8859-1?Q?efVHN7JmKVMxdUqHNgJr/Q2kuc6Z87/38tRVL1Umqf4QqX7FNkgUOJ0vmz?=
 =?iso-8859-1?Q?xTKJqgzhTQWeFFPqttUBpGdBHVCQ4J2O2GM4+M1AEkhWUdp/xgcvjUEqWC?=
 =?iso-8859-1?Q?vk8iZShO0yItI/G0qDTclcSPRLaWEUBjSkIZpbILc1FH3STkdDQXpcLrJa?=
 =?iso-8859-1?Q?+gRgVUF+30UFjD0D4EfrFnPTTC7ImfQBnMvMzMnVxEliawh5x423VpK9fK?=
 =?iso-8859-1?Q?jle4B9zFN22aF5SE/ufJJV7WYnOhFTypGReOam/bCz6VmCjzMNAOJwPYmV?=
 =?iso-8859-1?Q?AiYQPZHhPWYTHurvp81xxsI1rMBOnoSqPOmXD+r4PYolosWdMEXsWgpJTv?=
 =?iso-8859-1?Q?FZhYuY1sReNF3f0l8txfsKhUhvpRHCG04nfSkIx2aFhyC3zn7hkoj4dUjr?=
 =?iso-8859-1?Q?FWc8KPiJjFywe+gXgWL5sNo49f5gKYpn+432ifNynPd1peHhMbrCIQaQTc?=
 =?iso-8859-1?Q?7oPVOd5+LSLITXfCT58gl8YPpmpAULycopx/TpBeX/nYDhB3Aw1aLfUGvb?=
 =?iso-8859-1?Q?XJtd2WgXh1JEF/wnxNE/WBwC4LpyeIlzsVdtOJLVy+kpa0JoG/3RowOvjr?=
 =?iso-8859-1?Q?aG4opRevLh+vxuks3rQsNFxgFECSSTXPwPDK5t94ewdL+lvrGYWis82HZ8?=
 =?iso-8859-1?Q?UGRe4d2IY+jn6k/j94l/xEBBq4lisbVyxro6j8QYWgJ4USB880lCv//H6c?=
 =?iso-8859-1?Q?rqFXO2CuVdAluf8xY7o9tywO7EThqmpLE+3p+ZUblX8gCJfVQdNvt3VKvI?=
 =?iso-8859-1?Q?pplE1V3loZIdbID0CJ6IdP9baNfFgiYeFw/0o2JcgE7aNuvwhib/O2Jwl9?=
 =?iso-8859-1?Q?/bA4LMaFyadBe2nM2a30URfG3r0LZYGNrk0UrNOyApYy+R73wEIZ4rG1er?=
 =?iso-8859-1?Q?i7fjNSVW21SQNg8qcfkvOrM+aDXvQfyI2Zkg2qdw4BA7aCmr9FjF0ve/p1?=
 =?iso-8859-1?Q?aewYo+1/ReWeHIMrJvD8rOVwrpRkVQrjXOpOLrtJQEKz9/oAZhEZPKZBEr?=
 =?iso-8859-1?Q?rLmUuWD3cPffI9926lhSE8B4VhWHZX0OGRRWO2yPYUM87BUD6XNwWCxNrQ?=
 =?iso-8859-1?Q?fDkSwolkhFGV3p+IxPQdexvAJ8FVOneGHqOp01vFjf8g2LgPgS02ABgCtM?=
 =?iso-8859-1?Q?yhdVGJ4ELT7lFUUhfWUFgEHq8JJYWWQYkh9eAfTcR0IJJXSpxtvctAeNDY?=
 =?iso-8859-1?Q?9AnoA/KMIaq/LvQT5QCyjxuZH5Eh31YFdNHxxXRY9IlU8ZnLsV6O+FxIUk?=
 =?iso-8859-1?Q?JPPjGRGH7I/RSxTegZnOqNR4UXdA+p7ymp9W3fo1UyT6cktzfxBuwgizLl?=
 =?iso-8859-1?Q?X0Ph?=
Content-Type: multipart/alternative;
	boundary="_000_CWLP265MB462606402C5260979D4D9D15DCAB9CWLP265MB4626GBRP_"
  
  x-microsoft-antispam-message-info: hneRvPfPYH4UmMg/O/y8Hd5G5FyaKLfRdU/0XStHgrJLzjPEF3/B8cQCKhqlXhwfff4+L5SLpMXBD8lmYG0ZnL1FDrtMk0p+nNCvbfqRF8md6YFxJ6w5qG1AsTsb/KEtbiR/feTIW2fEMDeTI39/27fB/OF+T8yPkUDFGKKlP1Yl+en+/cfbrVtrhRX+jqSh9oeocqtVlC/qqci7kP6wj3wCFWHd6soCWZjBNLLR/a+phcXzNB3V+18eA7xiEntqrT7eNi8maMGPReH3aKkwZ6nCjLmLyNdkI7q12vRnji6toqj8z/HT5naz52HXipWAgWXP4MBWY5f1ivLzdifkBKJbc6awtSWiU/YZ+ZzCJdM3rvhGzFw2Eq9AgBR66uNllsWt6aSluVL9zEvDK99LoUP8W3cgD2i7hmRCVZZJVS+REQBFN0HK8Qq9T2Ohk3VELG38rzIckhf0SR7lCvI3HAPXOL6QARxOJnUg1FaXOYQm1TtubmRnKrbr8vcsuRHraxszWj7lSLU3z1JIUmHzwM+4e/4UMCnCjVnhwMODB1xydwPeh4DrmvppPvYAy6UwtvWefM0D9i4ykswDi0ltAL3Bc+ORKLTeR6sXwbwKrxc=
x-ms-exchange-antispam-messagedata-chunkcount: 1
x-ms-office365-filtering-correlation-id: ea2bd07c-4b0e-467a-46ed-08db15a82445
