name: Run pdk test unit

on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  validating:
    runs-on: [self-hosted-novum, self-hosted, linux]
    strategy:
      matrix:
        puppet-version: [5, 6, 7]
    steps:
    - name: Clone repository
      uses: actions/checkout@v2

    - name: Run pdk validate
      uses: puppets-epic-show-theatre/action-pdk-validate@v1
      with:
        puppet-version: ${{ matrix.puppet-version }}

  testing:
    runs-on: [self-hosted-novum, self-hosted, linux]
    strategy:
      matrix:
        puppet-version: [5, 6, 7]
    if: always()
    needs:
    - validating
    steps:
    - name: Clone repository
      uses: actions/checkout@v2

    - name: Run unit tests
      uses: puppets-epic-show-theatre/action-pdk-test-unit@v1
      # added because there are open ended dependencies version requirements in metadata.json
      with:
        puppet-version: ${{ matrix.puppet-version }}
